enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[Inotia00-YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
build-mode = "both"
included-patches = "'Custom branding icon MMT' 'MaterialYou'"
excluded-patches = "'Alternative thumbnails' 'Ambient mode switch' 'Append time stamps information' 'Change homepage' 'Custom branding name YouTube' 'Custom double tap length' 'Custom package name' 'Custom playback speed' 'Custom player overlay opacity' 'Custom seekbar color' 'Disable HDR video' 'Enable language switch' 'Enable tablet mini player' 'Enable tablet navigation bar' 'Enable wide search bar' 'Force fullscreen' 'Hide category bar' 'Hide channel avatar section' 'Hide channel profile components' 'Hide handle' 'Hide mix playlists' 'Hide music button' 'Hide navigation buttons' 'Hide navigation label' 'Hide shorts components' 'Layout switch' 'Overlay buttons' 'Return YouTube Dislike' 'SponsorBlock' 'Spoof device dimensions' 'Swipe controls' 'Theme' 'Translations'"

[Inotia00-Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom branding icon MMT'"
excluded-patches = "'Custom branding name YouTube Music' 'Custom package name' 'Custom playback speed' 'Enable black navigation bar' 'Enable color match player' 'Enable old style library shelf' 'Enable old style miniplayer' 'Enable zen mode' 'Hide action bar label' 'Hide button shelf' 'Hide carousel shelf' 'Hide category bar' 'Hide handle' 'Hide navigation bar component' 'Hide new playlist button' 'Hide playlist card' 'Hide radio button' 'Hook download button' 'Replace dismiss queue' 'Return YouTube Dislike' 'SponsorBlock' 'Start page' 'Translations'"

[ReVanced-YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"

[ReVanced-Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
